name: Python CI

on:
  pull_request:
    branches:
      - main  # PRの対象ブランチ

jobs:
  test:
    name: Run Python Tests and Lint
    runs-on: ubuntu-latest  # ジョブが実行される環境

    steps:
    # 1. GitHubリポジトリのコードをチェックアウト
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Python環境をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Pythonバージョンを3.9に固定

    # 3. 必要な依存関係をインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. コード品質チェック（例: flake8）
    - name: Run Linter (flake8)
      run: |
        pip install flake8
        flake8 .

    # 5. テストの実行（例: pytest）
    - name: Run Tests
      run: |
        pip inst
